<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ApplicationIcon>vr_icon.ico</ApplicationIcon>
    <AssemblyName>VRCapabilityChecker</AssemblyName>
    <RootNamespace>VRCapabilityChecker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="7.0.2" />
  </ItemGroup>

</Project>
